### ISSUE TITLE
thanks for the nice tool

### ISSUE THREAD

**Issue by ttlttc** [finzzz/gohfs#1]
this tool is much easier than nginx use.
and, will you make win-x86 version in future?i can use it on virtual hosting service.

**Comment by finzzz** [comment]
Hi, can you try using this https://github.com/finzzz/gohfs/releases/download/latest/gohfs-amd64.exe ?

**Comment by ttlttc** [comment]
sigh* 
dl&run it's tell me cannot run x64  application
(sys: win7 - x86)

**Comment by finzzz** [comment]
Ah I see, probably a good thing to update your system. Anyway, I'll add x64 in the future, but for now, you will have to build it yourself.
