### ISSUE TITLE
(win)404 when file/folder name contain space

### ISSUE THREAD

**Issue by ttlttc** [finzzz/gohfs#2]
"hello world.exe" solved as "hello%20world.exe", only show "404 page not found"

**Comment by ttlttc** [comment]
and a feature request: commandline switch to disable "upload" button(for anonymous user)

thanks.

**Comment by finzzz** [comment]
thanks for testing it out, I have applied hot fix to "file/folder containing space". Can you please try it again?

**Comment by finzzz** [comment]
> and a feature request: commandline switch to disable "upload" button(for anonymous user)
> 
> thanks.

As for disabling upload feature, it's on the roadmap, but I'm not sure what do you want to do by disabling it for anonymous user? Anonymous user cannot upload by default.

**Comment by ttlttc** [comment]
nice working, space glitch is gone~

deploy on vps and launched with 
-host 0.0.0.0
for all internet users, everyone can use "upload" function, it's not safe.

**Comment by ttlttc** [comment]
and something for default build parameter:

go build -ldflags "-w -s" main.go
optimized & decrease export file size lol

**Comment by finzzz** [comment]
> nice working, space glitch is gone~
> 
> deploy on vps and launched with
> -host 0.0.0.0
> for all internet users, everyone can use "upload" function, it's not safe.

I don't recommend you to do that, this app is still being tested.

**Comment by finzzz** [comment]
> and something for default build parameter:
> 
> go build -ldflags "-w -s" main.go
> optimized & decrease export file size lol

that's helpful! thanks

**Comment by ttlttc** [comment]
> s

okay. i'll close it when i finished transferring

**Comment by ttlttc** [comment]
problem solved, close.

and thanks again for your hard working~

**Comment by finzzz** [comment]
> problem solved, close.
> 
> and thanks again for your hard working~

Nope, zip and sha1 features still giving error.

**Comment by ttlttc** [comment]
haha, not a big things, at least up/dl is worked.
