### ISSUE TITLE
Feature Requests - Navigation

### ISSUE THREAD

**Issue by olofvndrhr** [finzzz/gohfs#6]
Hi, i would like to propose the feature of a navigation panel or just buttons to navigate in the webgui. Right now you have to manually change you path on the web server, but a "back" or "one folder up" button would greatly improve accessibility.

I have 2 examples on how it **_could_** look like. This is just for reference, the only notable things in the screenshots are the navigation options.

h5ai:
![image](https://user-images.githubusercontent.com/68583543/119201081-7b331600-ba8e-11eb-8355-46e4ba01c0e2.png)

minixed:
![image](https://user-images.githubusercontent.com/68583543/119201133-930a9a00-ba8e-11eb-9c17-f73483a339d7.png)

**Comment by jhjacobs81** [comment]
Yes, a basic gui for uploading and downloading, as well as folder creation etc would be much needed!

couple it with user accounts and you have a basic Nextcloud replacement (which becomes too bloated if you ask me)

**Comment by finzzz** [comment]
As long as it's not making the code too bloated, I will consider it. But, I'm not planning to implement user accounts.

**Comment by finzzz** [comment]
added in 0.1.4
